### ISSUE TITLE
GetAttachment() API not supporting /Type /F for File Specification dictionary

### ISSUE THREAD

**Issue by psemathi** [corymickelson/NoPoDoFo#90]
In PDF samples, where /Type /F has been used for File Specification dictionary instead of /Type /Filespec, nopodofo throws error that in turn terminates the application

nopodofo supports the following
4 0 obj 
<<
	/Type /Filespec
	/F (2019-03-21_26c77c1d955c9cb9a42def419e572d61897206ff.msg)
	/EF 
	<<
		/F 11 0 R
	>>
	/UF (2019-03-21_26c77c1d955c9cb9a42def419e572d61897206ff.msg)
>> 
endobj  

But nopodofo does not support the following
4 0 obj 
<<
	/Type /F
	/F (2019-03-08_941d7573ede8b1d99a09f8690dadc12bb4be5913.msg)
	/EF 
	<<
		/F 3 0 R
	>>
	/UF (þÿ 2 0 1 9 - 0 3 - 0 8 _ 9 4 1 d 7 5 7 3 e d e 8 b 1 d 9 9 a 0 9 f 8 6 9 0 d a d c 1 2 b b 4 b e 5 9 1 3 . m s g)
>> 
endobj

**Comment by psemathi** [comment]
To support /Type /F entry for File Specification dictionary, extended BaseDocument::GetAttachment as given below,. Could some one verify if this code is fine and if yes, could it be integrated in the next coming version.

BaseDocument::GetAttachment(const CallbackInfo& info)
{
/*
  return FileSpec::constructor.New({ External<PdfFileSpec>::New(
    info.Env(), base->GetAttachment(info[0].As<String>().Utf8Value())) });
*/
	stringstream msg;
	string name = info[0].As<String>();
    if(Logger::IsDebugEnabled()) Logger::LogDebug("GetAttachment: Parms: Attachment name:%s\n", name.c_str());
	if (base->GetAttachment(name)) {
		return FileSpec::constructor.New({ External<PdfObject>::New(
			info.Env(), base->GetAttachment(name)->GetObject()) });
	}
	
	if(base->GetNamesTree(false) == nullptr || base->GetNamesTree(false)->GetObject() == nullptr 
		|| base->GetNamesTree(false)->GetObject()->IsDictionary() == false
		|| base->GetNamesTree(false)->GetObject()->GetDictionary().HasKey(	Name::EMBEDDED_FILES) == false){
		if(Logger::IsDebugEnabled()) Logger::LogDebug("GetAttachment: PDF does not have any attachments\n");


		return info.Env().Null();
	}
	PdfObject* embeddedFiles =
		base->GetNamesTree(false)->GetObject()->MustGetIndirectKey(
			Name::EMBEDDED_FILES);
	if(embeddedFiles->GetDictionary().HasKey(Name::NAMES) &&
		embeddedFiles->MustGetIndirectKey(Name::NAMES)->IsArray()) {
		PdfObject* names = nullptr;
		PdfObject* filespec = nullptr;
		names = embeddedFiles->MustGetIndirectKey(Name::NAMES);
		for (auto&& ii : names->GetArray()) {
			PdfObject* item;
			filespec = nullptr;
			if (ii.IsReference()) {
				item = base->GetObjects()->GetObject(ii.GetReference());
			} 
			else { 
				item = &ii;
			}
			if (item->IsDictionary() && item->GetDictionary().HasKey(Name::TYPE) &&
				(item->GetDictionary().GetKey(Name::TYPE)->GetName() ==	Name::FILESPEC || item->GetDictionary().GetKey(Name::TYPE)->GetName() == "F" )) {
				filespec = item;

				if (filespec && filespec->GetDictionary().HasKey(Name::UF)) {
					PdfObject* uf = filespec->MustGetIndirectKey(Name::UF);
					if(Logger::IsDebugEnabled()) Logger::LogDebug("GetAttachment: PDF Attachment name:%s\n", uf->GetString().GetStringUtf8().c_str() );
					if (uf->IsString() && uf->GetString().GetStringUtf8() == name) {
						filespec->GetDictionary().RemoveKey(PdfName(Name::TYPE));
						filespec->GetDictionary().AddKey(PdfName(Name::TYPE), PdfName(Name::FILESPEC));
            			return FileSpec::constructor.New(
							{ External<PdfObject>::New(info.Env(), filespec) });
					}
				}
			}
		}
	}
	return info.Env().Null();
}

**Comment by corymickelson** [comment]
Thank you @psemathi I will take a look at this as soon as i can.

**Comment by corymickelson** [comment]
@psemathi Thank you for your contribution, there was a minor issue with the code above as the test documents have the file attachments under the "KIDS" property of the embedded files dictionary, but other than that I've added what you've provided above in the latest develop branch at 0b9a1305ac12e9e10c2220b5332331ac99202cf7 as a branching statement of the current BaseDocument::GetAttachment method. If you have any document(s) to run through testing I would be glad to add them to the current testing suite, otherwise if you could checkout the develop branch and try the GetAttachment again that would be appreciated.

**Comment by psemathi** [comment]
On 28-04-2019 08:18, Cory Mickelson wrote:
>
> @psemathi <https://github.com/psemathi> Thank you for your 
> contribution, there was a minor issue with the code above as the test 
> documents have the file attachments under the "KIDS" property of the 
> embedded files dictionary, but other than that I've added what you've 
> provided above in the latest develop branch at 0b9a130 
> <https://github.com/corymickelson/NoPoDoFo/commit/0b9a1305ac12e9e10c2220b5332331ac99202cf7> 
> as a branching statement of the current BaseDocument::GetAttachment 
> method. If you have any document(s) to run through testing I would be 
> glad to add them to the current testing suite, otherwise if you could 
> checkout the develop branch and try the GetAttachment again that would 
> be appreciated.
>
Thank you for the information and the correction of the fix. The sample 
I tested is from the customer, so I created a similar sample for your 
testing and attached the same here. Please use it.

Regards,
Mathi

**Comment by corymickelson** [comment]
Thank you, I however do not see any attachments to this email. Could you
please try sending them again?
Thank you,
Cory

**Comment by psemathi** [comment]
On 06-05-2019 20:57, Cory Mickelson wrote:
> Thank you, I however do not see any attachments to this email. Could you
> please try sending them again?
Here it is again.

> Thank you,
> Cory
>
